### ISSUE TITLE
Sorry, I did not get how to use this on client side. 

### ISSUE THREAD

**Issue by belokonm** [copleykj/meteor-simple-publish#1]
Can you share some example ,please?

**Comment by copleykj** [comment]
This package only runs server side and publishes data to your collections on the client.. You access the data through the collections just as you would if you just published a cursor from the publication.

**Comment by belokonm** [comment]
thank you for your respond, but it is still did not answer on my question. 
If I have 2 collections books and users. 
books {_id, title, userId} users:{_id, name, surname}
How I should access to User name?
books.users.name or books.name or your variant ,please?
