### ISSUE TITLE
many-to-many support

### ISSUE THREAD

**Issue by pward123** [copleykj/meteor-simple-publish#2]
Does this support many-to-many joins?

i.e. allowing an array for the inverted foreign key

**Comment by copleykj** [comment]
It should, but to be truly honest I've yet to have a use for a many to many join and its been what seems like forever since I first wrote the code for this.

**Comment by copleykj** [comment]
I've also been contemplating a total refactoring of this package, but I've been hesitant in hopes that MDG will finally cross this off the Roadmap with an official way to accomplish joins. I'm sure they could create a much cleaner implementation with their superior knowledge of the they way livequery works.

**Comment by pward123** [comment]
Agreed. This is number 2 on my list of things MDG needs to address soon.  Going to close this till I give it another go.  This is my first time trying simple-publish, but I've been a long time fan of Mesosphere.
